use ferrotick_core::{Symbol, UtcDateTime};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderSide {
    Buy,
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderType {
    Market,
    Limit,
    Stop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderStatus {
    New,
    Filled,
    Cancelled,
    Rejected,
}

/// Order representation used by the backtest engine.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Order {
    pub id: Uuid,
    pub symbol: Symbol,
    pub side: OrderSide,
    pub order_type: OrderType,
    pub quantity: f64,
    pub limit_price: Option<f64>,
    pub stop_price: Option<f64>,
    pub created_at: UtcDateTime,
    pub status: OrderStatus,
}

impl Order {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        symbol: Symbol,
        side: OrderSide,
        order_type: OrderType,
        quantity: f64,
        limit_price: Option<f64>,
        stop_price: Option<f64>,
        created_at: UtcDateTime,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            symbol,
            side,
            order_type,
            quantity,
            limit_price,
            stop_price,
            created_at,
            status: OrderStatus::New,
        }
    }

    pub fn market_buy(symbol: Symbol, quantity: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Buy,
            OrderType::Market,
            quantity,
            None,
            None,
            UtcDateTime::now(),
        )
    }

    pub fn market_sell(symbol: Symbol, quantity: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Sell,
            OrderType::Market,
            quantity,
            None,
            None,
            UtcDateTime::now(),
        )
    }

    pub fn limit_buy(symbol: Symbol, quantity: f64, limit_price: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Buy,
            OrderType::Limit,
            quantity,
            Some(limit_price),
            None,
            UtcDateTime::now(),
        )
    }

    pub fn limit_sell(symbol: Symbol, quantity: f64, limit_price: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Sell,
            OrderType::Limit,
            quantity,
            Some(limit_price),
            None,
            UtcDateTime::now(),
        )
    }

    pub fn stop_buy(symbol: Symbol, quantity: f64, stop_price: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Buy,
            OrderType::Stop,
            quantity,
            None,
            Some(stop_price),
            UtcDateTime::now(),
        )
    }

    pub fn stop_sell(symbol: Symbol, quantity: f64, stop_price: f64) -> Self {
        Self::new(
            symbol,
            OrderSide::Sell,
            OrderType::Stop,
            quantity,
            None,
            Some(stop_price),
            UtcDateTime::now(),
        )
    }

    pub fn notional(&self, execution_price: f64) -> f64 {
        self.quantity * execution_price
    }
}

/// Executed fill generated by the order executor.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Fill {
    pub order_id: Uuid,
    pub symbol: Symbol,
    pub side: OrderSide,
    pub quantity: f64,
    pub price: f64,
    pub gross_value: f64,
    pub fees: f64,
    pub slippage: f64,
    pub filled_at: UtcDateTime,
}

impl Fill {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        order_id: Uuid,
        symbol: Symbol,
        side: OrderSide,
        quantity: f64,
        price: f64,
        fees: f64,
        slippage: f64,
        filled_at: UtcDateTime,
    ) -> Self {
        Self {
            order_id,
            symbol,
            side,
            quantity,
            price,
            gross_value: quantity * price,
            fees,
            slippage,
            filled_at,
        }
    }

    /// Cash flow from the perspective of portfolio cash.
    pub fn net_cash_flow(&self) -> f64 {
        match self.side {
            OrderSide::Buy => -(self.gross_value + self.fees),
            OrderSide::Sell => self.gross_value - self.fees,
        }
    }
}
